### ISSUE TITLE
请教 end-to-end audiovisual speech recognition的.npy的文件生成问题

### ISSUE THREAD

**Issue by wanli4717** [sailordiary/LipNet-PyTorch#1]
我是天津大学的一名研究生，，目前在复现end-to-end audiovisual  speech recognition 论文实验结果，我看见了您在博主的git上留言了，并发现了其中的错误，我想找您请教一下那篇论文生成.npy的文件问题

**Comment by sailordiary** [comment]
Hi,

You can refer to https://github.com/mpc001/end-to-end-lipreading/issues/6#issuecomment-449582378 . The expected format is a numpy array of shape [29, 96, 96]. If you want to save the videos as npy files just do an `np.save` on the array of stacked frames (i.e. `batch_feats`).
